# Generated by Django 5.1.2 on 2025-10-19 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gift', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='party.party')),
            ],
        ),
    ]
