# Generated by Django 5.1.2 on 2025-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=False),
        ),
    ]
